//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectofinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class asientos
    {
        public int Idasiento { get; set; }
        public Nullable<int> autobus { get; set; }
        public Nullable<int> asientonumero { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual bus bus { get; set; }
    }
}
