//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectofinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasaje
    {
        public int Idpasaje { get; set; }
        public string nombrepasajero { get; set; }
        public Nullable<int> origen { get; set; }
        public Nullable<int> destino { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fechasalida { get; set; }
        public string patente { get; set; }
        public string chofer { get; set; }
        public Nullable<int> precio { get; set; }
        public string auxiliar { get; set; }
        public Nullable<int> asiento { get; set; }
    
        public virtual salidabus salidabus { get; set; }
    }
}
