//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectofinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class salidabus
    {
        public int Idsalida { get; set; }
        public string chofer { get; set; }
        public string auxiliar { get; set; }
        public Nullable<int> bus { get; set; }
        public string fecha_salida { get; set; }
        public Nullable<int> destino { get; set; }
        public Nullable<int> origen { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual bus bus1 { get; set; }
        public virtual ciudad ciudad { get; set; }
        public virtual ciudad ciudad1 { get; set; }
        public virtual pasaje pasaje { get; set; }
    }
}
